// <auto-generated />
using System;
using ExamArchive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamArchive.Migrations
{
    [DbContext(typeof(ExamArchiveDbContext))]
    [Migration("20260814114037_AddPaperFiles")]
    partial class AddPaperFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudiesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudiesId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("ExamArchive.Models.MajorSubject", b =>
                {
                    b.Property<int>("MajorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("INTEGER");

                    b.HasKey("MajorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("MajorSubjects");
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Year", "Month");

                    b.ToTable("Papers", t =>
                        {
                            t.HasCheckConstraint("CK_Paper_ExamType", "[ExamType] IN ('Midterm', 'Final', 'Resit')");

                            t.HasCheckConstraint("CK_Paper_Month", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_Paper_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.PaperFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaperId", "PageNumber")
                        .IsUnique();

                    b.ToTable("PaperFiles", t =>
                        {
                            t.HasCheckConstraint("CK_PaperFile_ContentType", "[ContentType] IN ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')");

                            t.HasCheckConstraint("CK_PaperFile_PageNumber", "[PageNumber] >= 1");

                            t.HasCheckConstraint("CK_PaperFile_SizeBytes", "[SizeBytes] >= 0");
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Studies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor's"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Master's"
                        });
                });

            modelBuilder.Entity("ExamArchive.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.HasOne("ExamArchive.Models.Studies", "Studies")
                        .WithMany("Majors")
                        .HasForeignKey("StudiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("ExamArchive.Models.MajorSubject", b =>
                {
                    b.HasOne("ExamArchive.Models.Major", "Major")
                        .WithMany("MajorSubjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamArchive.Models.Subject", "Subject")
                        .WithMany("MajorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.HasOne("ExamArchive.Models.Subject", "Subject")
                        .WithMany("Papers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamArchive.Models.PaperFile", b =>
                {
                    b.HasOne("ExamArchive.Models.Paper", "Paper")
                        .WithMany("Files")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ExamArchive.Models.Major", b =>
                {
                    b.Navigation("MajorSubjects");
                });

            modelBuilder.Entity("ExamArchive.Models.Paper", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ExamArchive.Models.Studies", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("ExamArchive.Models.Subject", b =>
                {
                    b.Navigation("MajorSubjects");

                    b.Navigation("Papers");
                });
#pragma warning restore 612, 618
        }
    }
}
